### ISSUE TITLE
Failing to open links, starting with "www."

### ISSUE THREAD

**Issue by ghost** [Garee/sp#1] opened 2018-12-06 09:09 UTC
Started using this tool, very useful, thank you for your work. 
Anyway, found a bug: when results starts with "www.", and i try to open it - i get error: 
`gvfs-open: www.xyz.com: error opening location: Error when getting information for file '/home/USER/www.xyz.com': No such file or directory.`
sp version: 1.0.0
OS: Debian 9. 
EDIT: Added an example screenshot.
EDIT2: Realised, that there wasn't any reference to error on the screenshot and deleted it.

**Comment by Garee** [comment] 2018-12-06 19:04
Thanks for reporting this issue @d34dm8.

I can't reproduce the error message, but I can see that links without a scheme fail to open. What is your default browser?

I'll include a fix for this in the next release.

**Comment by Garee** [comment] 2018-12-06 20:27
Please update `sp` and let me know if the release `1.0.1` has resolved this issue for you:

`pip install --upgrade spcli`

**Comment by ghost** [comment] 2018-12-07 05:01
Thank you for your quick response!
My browser is Firefox 60.
Thing is - it's a problem with xdg-open/gvfs open: they can't open a url without scheme (http/https/ftp/etc), so when you ask them to open "www.something.com", they think it's a file.
You can test it just like this:
`$ xdg-open www.something.com`
`gvfs-open: www.something.com: error opening location: Error when getting information for file '/home/user/www.something.com': No such file or directory
`
I'll try to update and tell you about results little later.

**Comment by ghost** [comment] 2018-12-07 05:04
Upgrade did it, now everything opens just fine! You can close this issue :3
Thank you for your work!

**Closed as completed** 2018-12-07 11:45 UTC
Labels: bug
