### ISSUE TITLE
No search results

### ISSUE THREAD

**Issue by RogerPAlexander** [Garee/sp#10] opened 2021-06-08 20:54 UTC
Sorry if I'm being dense, but I get no search results from sp anymore.

The output of "sp --debug hello world" is attached.
[sp-debug-output.txt](https://github.com/Garee/sp/files/6619548/sp-debug-output.txt)

**Comment by Garee** [comment] 2021-06-09 09:00
Hello @RogerPAlexander, can you please try again and confirm whether it is working now?

I have tried to reproduce this, but I can successfully see the results for "hello world".

**Comment by RogerPAlexander** [comment] 2021-06-09 09:08
still the same after reinstall –– the debug output has a reply line with HTTP code 200, meaning it succeeded, but all the other lines are headers with no actual contents. Can you post the output you get from "sp --debug hello world"?

Does python2 vs python3 matter? I used pip3 to install with no warnings or errors.

**Comment by RogerPAlexander** [comment] 2021-06-09 09:09
I've been using sp in a Perl script to collect specific Twitter handles. Very useful, but it just stopped working one day.

**Comment by Garee** [comment] 2021-06-09 09:23
@RogerPAlexander I just released version `1.0.4` which should address this problem. Please update and let me know if it works for you:

`pip install spcli -U`

**Comment by ghost** [comment] 2021-06-09 12:55
I have the same problem, and to be fair, the problem isn't in the program, it's just since last three or four month Startpage started applying strickter rules for using its services.
For example, i use Firefox with turned-off cookies, and turn them on for only specific site: and for the same period more ofter than not Starpage just shows me "Just checkin in..", with some text about me using Tor network. Even though i wasn't connecting through tor network.
Since then spcli also started acting weird, i even tried to change UserAgent, nothing helps.
Ironically, sometimes it helps to send program's traffic through Tor :) But most of the time it just doesn't work.

**Comment by Garee** [comment] 2021-06-12 13:46
I'm going to close this issue as I believe the latest package version is working. Please let me know if this is not the case.

Unfortunately, this package relies on the startpage.com implementation not introducing a breaking change. I need to stay on top of any updates.

**Closed as completed by Garee** 2021-06-12 13:46 UTC

**Comment by RogerPAlexander** [comment] 2021-06-12 17:28
I'm sorry, @Garee, I thought I had responded. 

pip install spcli -U

did in fact fix the problem for me!  Thank you!
